# 1. Cấu hình kết nối SQL Server của mày
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=job_platform;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123456

# 2. Cấu hình Hibernate (JPA)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ddl-auto = validate: Nó sẽ kiểm tra xem cấu trúc Java sau này mình viết có khớp với bảng dưới DB không.
# Vì mày đã chạy file file job_platform.sql tạo bảng sẵn rồi nên để validate là chuẩn nhất.
spring.jpa.hibernate.ddl-auto=validate

# Hiển thị câu lệnh SQL ra màn hình Console để tiện debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Đổi cổng chạy của dự án từ 8080 sang 8090 cho đỡ bị tranh chấp
server.port=8090